import Faqs from "../Footstub/faqmid.js"
import React from "react"

export default props => {
    return(
    <div>
        <Faqs arraycontent={[{
                topichead:"Terms of use",
                content: "GLADS is a wholly owned unit of Evergreencube Solution PVT. LTD.. Trademark and copyrights are owned by the company Evergreencube Solution PVT. LTD.. This document is an electronic record in terms of the Information Technology Act, 2000, and rules there under, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.glads.co.in and application in app store in play store.",
                extend:"Read more",
                to:"/termsConditions"
            },

            

            {
                topichead:"Cancellations And Refunds",
                content: "You cannot cancel an order after it has been confirmed.If you are not present at the pick-up site within a reasonable time of the arrival of our executive, are found to have provided incorrect contact or location details or an address that lies outside our serviceable area, are unresponsive to attempted communication, fail to make payment in case of Cash on Pick-Up or refuse the service being provided to you, your order will be cancelled with no possibility of refund and in case of Cash on Pick-Up, your account will be charged a cancellation fee",
                to:"/refundAndCancellation",
                extend:"Read more"
            }
        ]}/>


    </div>





    )
    }