import Legals from "../Footstub/faqmid.js"
import React from "react"

export default props => {
    return(
    <div>
        <Legals arraycontent={[{
                topichead:"Terms of use",
                content: "GLADS is a wholly owned unit of Evergreencube Solution PVT. LTD.. Trademark and copyrights are owned by the company Evergreencube Solution PVT. LTD.. This document is an electronic record in terms of the Information Technology Act, 2000, and rules there under, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.glads.co.in and application in app store in play store.",
                extend:"Read more",
                to:"/termsConditions"
            },

            {
                topichead:"Privacy Policy",
                content: "At Evergreencube Solution Pvt. Ltd. (“us”, “we”, “our” or “Company”), we hold in the utmost respect our users’ privacy and strive to create a platform (“GLADS”) that is committed to protecting this privacy.This Privacy Policy (“Policy”) describes the procedures followed for the collection, use and disclosure of your information on the website www.glads.co.in // and/or the mobile application GLADS (collectively “platform”) by Evergreencube Solution Pvt. Ltd., a company established under the laws of India and having its registered office at MNIT Innovation and Incubation Centre, Malaviya National Institute of Technology, Jawahar Lal Nehru Marg, Jhalana Gram, Malviya Nagar, Jaipur, Rajasthan - 302017.",
                extend:"Read more",
                to:"/privacyPolicy"
            },

            {
                topichead:"Cancellations And Refunds",
                content: "You cannot cancel an order after it has been confirmed.If you are not present at the pick-up site within a reasonable time of the arrival of our executive, are found to have provided incorrect contact or location details or an address that lies outside our serviceable area, are unresponsive to attempted communication, fail to make payment in case of Cash on Pick-Up or refuse the service being provided to you, your order will be cancelled with no possibility of refund and in case of Cash on Pick-Up, your account will be charged a cancellation fee",
                to:"/refundAndCancellation",
                extend:"Read more"
            }
        ]}/>


    </div>





    )
    }