import React from "react"
import Pagebox from  "../components/Footer/pagebox.module.css"
import Legalheader from "../components/Footstub/legalHeader.js"
import Footer from "../components/FooterMain/Footer.js"



export default () => (
<div>
    <Legalheader heading={"TERMS & CONDITIONS"}/>
   
<div className={Pagebox.container}>

    
    <p>GLADS is a wholly owned unit of <b>Evergreencube Solution PVT. LTD.</b>. Trademark and copyrights are owned by the company Evergreencube Solution PVT. LTD.. This document is an electronic record in terms of the Information Technology Act, 2000, and rules there under, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.glads.co.in and application in app store in play store.</p><br/>

    <h3>SECTION 1A - MOBILE APP TERMS</h3>
    <p>Use of the Mobile App.</p>
    <p><strong>General</strong>- In addition to the terms set forth in this Agreement, Your use of the App is subject to the following additional terms (the "App Terms"): You understand and agree that:  </p>
    <ol><li>
	<p>Your use of the App is conditioned upon Your acceptance of these App Terms,</p><ul>
	<li><p>the App contains copyrighted material, trade secrets, and other proprietary materials of <strong>Evergreencube Solution PVT. LTD. </strong> and its licensors, and</p></li>
	<li><p>in order to protect those proprietary materials, except as expressly permitted by applicable law, neither You nor a third party acting on Your behalf will: </p></li><ul>
	<li>decompile, disassemble or reverse engineer the App;</li>
	<li>modify or create derivative works of the App;</li>
	<li>use the App in any manner to provide service bureau, commercial time-sharing or other computer services to third parties;</li>
	<li>transmit the App or provide its functionality, in whole or in part, over the Internet or other network (except as expressly permitted above);</li>
	<li>sell, distribute, rent, lease, sublicense or otherwise transfer the App to a third party; or</li>
	<li>use components of the App to run applications not running on the App.</li></ul></ul></li>
	<li><p>App User Agreement. YOU HEREBY AGREE:</p><ul>
	<li>to only use the Website/App to access and/or use the Services;</li>
	<li>to not use any software or services in conjunction with the Service or authorized third-party software which modifies or reroutes, or attempts to modify or reroute, the Service;</li>
	<li>will not authorize any third party to access and/or use the Service on Your behalf using any automated process such as a BOT, a spider or periodic caching of information stored by the Service on Your behalf without a separate written agreement with <strong>Evergreencube Solution PVT. LTD. </strong></li>
	<li>will not use any software or hardware that reduces the number of Users directly accessing or using the Service (sometimes called 'multiplexing' or 'pooling' software or hardware);</li>
	<li>will not lend, lease, rent or sublicense the App;</li>
	<li>to permit <strong>Evergreencube Solution PVT. LTD.</strong> to send and deliver updates to You as part of Your use of the App; and</li>
	<li>to allow the App to automatically download and install updates from time to time from <strong>Evergreencube Solution PVT. LTD. </strong> which is designed to improve, enhance and further develop the App and may take the form of bug fixes, enhanced functions, new software modules and completely new versions.</li></ul></li></ol>
    
    <h3>SECTION 1B - ONLINE STORE TERMS</h3>
    
    <p>By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.</p>
    <p>You may not use our products or services for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws). You must not transmit any worms or viruses or any code of a destructive nature.</p>
    <p>You are hereby authorized by <strong>Evergreencube Solution PVT. </strong> LTD. to view, download, copy and print documents and the graphics incorporated therein ("materials") from this website subject to the following restrictions and in accordance with any written agreement between you and <strong>Evergreencube Solution PVT. LTD. </strong>.</p><ol>
    	<li>The materials may be used solely by you for your own personal informational, educational or other non-commercial purposes unless otherwise expressly indicated;</li>
    	<li>All copies you make must properly attribute the appropriate source, including any copyright or other proprietary notices originally shown or included in the materials;</li>
    	<li>You may not modify any of the materials found at this website unless otherwise expressly indicated, nor attempt to pass off any materials found at this website as your own;</li>
    	<li>You may not use, reproduce or publicly display or perform, or distribute any of the materials within this website for any commercial or public purpose, unless <strong>Evergreencube Solution PVT. LTD. </strong> has given you prior written consent to do so;</li>
    	<li>You may not "mirror" or "frame" any portions of this website in any other environment without prior written consent from <strong>Evergreencube Solution PVT. LTD. </strong></li>
    	<li>You may not display or transmit <strong>Evergreencube Solution PVT. LTD. </strong> RSS feed content in a manner that does not permit successful linking to, redirection to, or delivery of the applicable official <strong>Evergreencube Solution PVT. LTD. </strong> URL, and you may not insert any intermediate page, splash page, or other content between the <strong>Evergreencube Solution PVT. LTD. </strong>. RSS link and the applicable official <strong> Evergreencube Solution PVT. LTD. </strong> URL.</li></ol>
    <p><strong>Evergreencube Solution PVT. LTD. </strong> reserves the right to terminate the access of any user in its sole discretion, including users that do not observe these Terms and Conditions or who infringe or otherwise violate the rights of others. You agree that you are expressly prohibited from using any materials found on this website to the detriment of <strong>Evergreencube Solution PVT. LTD. </strong> or its affiliates in any type of patent infringement proceeding.
    Your failure to comply with this prohibition constitutes copyright infringement of the materials at issue. Each instance of noncompliance with this prohibition constitutes a separate instance of infringement, and subjects you to a payment obligation as liquidated damages and not as a penalty. A breach or violation of any of the Terms will result in an immediate termination of our Services.</p>
    <p>You are prohibited from posting or transmitting to <strong>Evergreencube Solution PVT. LTD. </strong> via this website, any material that is unlawful, obscene, pornographic, libellous, threatening, or otherwise inappropriate.</p>
    
    <h3>SECTION 2 - GENERAL CONDITIONS (FOR SERVICE BOY)</h3><ol>
    
    	<li>All the information given by you to the company officials should be correct. Anything found suspicious will lead to strict action by the company.</li>
    	<li>The company reserves the right to decide the amount to be paid for each successful delivery/pickup.</li>
    	<li>You are solely responsible for successful delivery of the stuff and no carelessness, misbehaviour or unreasonable delays shall be entertained.</li>
    	<li>In case of damages occurred during the course of delivery/pickup, you will be fined according to the company’s refund policy.</li>
    	<li>Bags and T-shirts given to you will be rechecked by company officials every month; failing to produce appropriate stuff might cause your service to be temporarily or even permanently terminated.</li>
    	<li>Any nuisance reported by the customer, laundry or anyone concerned shall be processed fairly and may lead to the deducted payments or even the termination.</li>
    	<li>The t-shirt shall be worn during the time of pickup and delivery. </li></ol>
    
    
    
    <h3>SECTION 3 - ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION</h3>
    <p>We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or timelier sources of information. Any reliance on the material on this site is at your own risk. This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site.</p>
    
    <h3>SECTION 4 - MODIFICATIONS TO THE SERVICE AND PRICES</h3>
    <p>Prices for our services are subject to change without notice. We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time. We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.</p>
    
    <h3>SECTION 5 - PRODUCTS OR SERVICES</h3>
    <p>Certain services may be available exclusively online through the website. These services may have limited quantities. We reserve the right, but are not obligated, to limit the sales of our services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any services that we offer. All descriptions of services are subject to change at any time without notice, at the sole discretion of us. We reserve the right to discontinue any service at any time. Any offer for any service made on this site is void where prohibited.</p>
    
    <h3>SECTION 6 - OPTIONAL TOOLS</h3>
    <p>We may provide you with access to third-party tools. You acknowledge and agree that we provide access to such tools “as is” and “as available” without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools.</p><p>
    Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).</p><p>
    We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service.</p>
    <h3>SECTION 7 - THIRD-PARTY LINKS</h3>
    <p>Certain content and services available via our service may include materials from third-parties. Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other, or services of third-parties.</p><p>
    We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party services should be directed to the third-party.</p>
    
    <h3>SECTION 8 - USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS</h3>
    <p>If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.</p><p>
    We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.</p><p>
    You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libellous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.</p>
    
    <h3>SECTION 9 - PERSONAL INFORMATION</h3>
    <p>Your submission of personal information through the store is governed by our Privacy Policy</p>
    
    <h3>SECTION 10 - ERRORS, INACCURACIES AND OMISSIONS</h3>
    <p>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to service descriptions, pricing, promotions, offers, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order). We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website should be taken to indicate that all information in the Service or on any related website has been modified or updated.</p>
    
    <h3>SECTION 11 - PROHIBITED USES</h3>
    <p>In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, Pharm., pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
    
    <h3>SECTION 12 - DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</h3>
    <p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free. We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable. You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.</p>
    <p>You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
    <p>In no case shall <strong>Evergreencube Solution PVT. LTD. </strong>, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
    
    <h3>SECTION 13 – INDEMNIFICATION</h3>
    <p>You agree to indemnify, defend and hold harmless Evergreencube Solution PVT. LTD.. and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>
    
    <h3>SECTION 14 – SEVERABILITY</h3>
    <p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
    
    <h3>SECTION 15 – TERMINATION</h3>
    <p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes. These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site. If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p>
    
    <h3>SECTION 16 - ENTIRE AGREEMENT</h3>
    <p>The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service). Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>
    
    <h3>SECTION 17 - GOVERNING LAW</h3>
    <p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the all laws under Indian Penal Code.</p>
    
    <h3>SECTION 18 - CHANGES TO TERMS OF SERVICE</h3>
    <p>You can review the most current version of the Terms of Service at any time at this page. We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p>
    
    <h3>SECTION 19- TERMS FOR USING OUR SERVICE</h3><ol><li>
    	Clothes need to be counted at the time of pick-up in front of the delivery agent and any discrepancy should be notified immediately to the agent and to us by email to support@YOURSDHOBI.com  giving details of your order number.</li>
    	<li>Clothes will be handed over to security or friend or neighbor in case of customer not being available only when a written confirmation is provided from the customer in the form of an e-mail from your registered email address with us.</li>
    	<li>The company will need minimum 7 days after the day of complaint to give an update on the issues raised.</li>
    	<li>The company tries to deliver clothes on time but sometimes due to unforeseeable circumstances there might be a delay in delivery.</li>
    	<li>Some stains are very tough and not covered under <strong>Evergreencube solution PVT. LTD.</strong>service agreement. So, if the stains don’t go, we will not be held responsible.</li>
    	<li>In case of damage to a cloth, the damage should be reported to the company within 1 day of delivery.</li>
    	<li>In case of damage to a cloth, the company will try to rectify the damage. In case of failure in doing that, 10 times the amount of the service availed for, will be reimbursed. Please refer general conditions for more details.</li>
    	<li>We take special care in handling all types of clothes. But, due to the basic property of some clothes, they will bleed colors on their own. In such cases, company won’t be liable for any loss.</li>
    	<li>The company is not responsible if the customer forgets something in the clothes and it gets damaged and/or misplaced.</li>
    	<li>It is a strict policy of the company to not process damaged, torn, or stained clothes. It will be done only on special request and written approval by an email from the registered email address with us.</li></ol>
    <h3>SECTION 20 - TERMS FOR USING EXPRESS SERVICE</h3><ol><li>
    	If your laundry is ready before the selected time slot, we will make a call and confirm your availability.</li>
    	<li>Cost of express service is 2 times normal service listed on website.</li>
    	<li>Any offer listed for regular service does not apply for express service.</li>
    	<li>There might be unforeseen delays in delivery by any natural calamity and traffic.</li>
    	<li>We are not responsible for the stains and damaged clothes after they have been collected from you.</li>
    	<li>If damage is caused due to washing, we are liable for maximum of 10 times the service cost for that cloth.</li>
    	<li>Invoice will be sent by mail to registered email id and through the mobile application. Invoice amount may be also sent as an SMS for every order.</li>
    	<li>If COD (Cash on Delivery) is the chosen method of payment, you are liable to pay the amount sent through invoice when clothes are picked up.</li>
    	<li>Terms and conditions are subject to changes at any point of time and you will be notified about the same.</li> </ol>
    
    <h3>SECTION 21- REFUND POLICY</h3>
    <p><strong>Evergreencube Solution PVT. LTD.</strong>, provides refund in some circumstances which will be decided by company and can be changed by company.</p>
    
    
    <h3>SECTION 22 - CONTACT INFORMATION</h3>
    <p>Queries or Questions about the Terms of Service should be sent at <em>support@YOURSDHOBI.com</em></p>  
    </div>
    <Footer/>  

   
    </div>
    
)
    

